### ISSUE TITLE
Liens morts dans le README

### ISSUE THREAD

**Issue by cglacet** [dimitri-bourreau/2n#3]
## Lien vers le jeu

Le lien vers [le jeu](https://2n.dimitribourreau.me/) n'est [pas le bon](https://dimitribourreau.me/2n). D'ailleurs autant mettre le lien directement sur l'image : 

<div align="center">
    <a href="https://2n.dimitribourreau.me/">
        <img src="https://github.com/tobudim/2n/blob/master/readme/game.png?raw=true"/>
    </a>
</div>

Et le rappeler en haut du readme (pour les gens qui ne comprendraient pas qu'on peut cliquer sur l'image). 

## Lien vers la version anglaise

J'imagine qu'il serait mieux tout en haut de page (si on ne lit pas le français on ira surement pas chercher le lien en anglais). Le lien actuel n'est pas le bon.

**Comment by tobudim** [comment]
(tu es un gars en or)

Merci c'est une très bonne idée, je m'en occupe de suite. 🙋‍♂️

**Comment by miyucode** [comment]
Je tiens à prévenir que le lien est encore mort (le lien [https://2n.dimitribourreau.me](url) ne fonctionne en aucun cas.

**Comment by dimitri-bourreau** [comment]
Dans ce cas de figure @miyucode je te recommande de prendre cette habitude :
- Créer une nouvelle issue.
- Citer l'issue fermée. 👍

Mais oui, j'ai lâché le projet, je devrais changer le readme.
Tiens bah, @miyucode , tu veux pas t'entraîner à forker + proposer une PR ?

Il faudrait changer le Readme pour qu'il ne fasse plus référence à la version en ligne.
