### ISSUE TITLE
Le lien me dirigant vers Pilotest (dans le README) est dit "malveillant" par n'importe quel navigateur.

### ISSUE THREAD

**Issue by miyucode** [dimitri-bourreau/2n#5]
Microsoft Edge me dis que le site serait malveillant, une capture d'écran pour confirmer l'issue:
![preuve github pilotest site malveillant](https://user-images.githubusercontent.com/75862582/126865641-cc382bea-e7ce-4c41-8e28-1e7462c3ac39.png)

**Comment by miyucode** [comment]
Je sais pas si ça le fait que de mon côté, mais même avec Firefox ou encore Google Chrome ça me fait pareil :/
Problème d'url ? Ou juste que c'est vraiment malveillant ?

**Comment by dimitri-bourreau** [comment]
Ce n'est pas un problème lié à mon application, du coup. 🙂
Cependant, c'est un défaut de certificat à priori (certificat SSL si tu veux te renseigner).

Néanmoins tu n'as pas grand risque à aller tout de même sur le site : ils ne te demanderont pas d'informations personnelles sinon un email pour créer un compte. 😄

Je ferme l'issue du coup. 👍
